// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThePleasantOcc.Data;

#nullable disable

namespace ThePleasantOcc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309025729_CleanStart")]
    partial class CleanStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThePleasantOcc.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ThePleasantOcc.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("OccupiedBeds")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "single",
                            RoomNumber = "101",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 2,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "single",
                            RoomNumber = "102",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 3,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "single",
                            RoomNumber = "103",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 4,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "single",
                            RoomNumber = "104",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 5,
                            Floor = 2,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "single",
                            RoomNumber = "201",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 6,
                            Floor = 2,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "single",
                            RoomNumber = "202",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 7,
                            Floor = 2,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "single",
                            RoomNumber = "203",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 8,
                            Floor = 2,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "single",
                            RoomNumber = "204",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 9,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2800m,
                            Residence = "double",
                            RoomNumber = "101",
                            RoomType = "Double",
                            Size = "28m²",
                            TotalBeds = 2
                        },
                        new
                        {
                            Id = 10,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2800m,
                            Residence = "double",
                            RoomNumber = "102",
                            RoomType = "Double",
                            Size = "28m²",
                            TotalBeds = 2
                        },
                        new
                        {
                            Id = 11,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2800m,
                            Residence = "double",
                            RoomNumber = "103",
                            RoomType = "Double",
                            Size = "28m²",
                            TotalBeds = 2
                        },
                        new
                        {
                            Id = 12,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2800m,
                            Residence = "double",
                            RoomNumber = "104",
                            RoomType = "Double",
                            Size = "28m²",
                            TotalBeds = 2
                        },
                        new
                        {
                            Id = 13,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2200m,
                            Residence = "triple",
                            RoomNumber = "101",
                            RoomType = "Triple",
                            Size = "35m²",
                            TotalBeds = 3
                        },
                        new
                        {
                            Id = 14,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2200m,
                            Residence = "triple",
                            RoomNumber = "102",
                            RoomType = "Triple",
                            Size = "35m²",
                            TotalBeds = 3
                        },
                        new
                        {
                            Id = 15,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2200m,
                            Residence = "triple",
                            RoomNumber = "103",
                            RoomType = "Triple",
                            Size = "35m²",
                            TotalBeds = 3
                        },
                        new
                        {
                            Id = 16,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2200m,
                            Residence = "triple",
                            RoomNumber = "104",
                            RoomType = "Triple",
                            Size = "35m²",
                            TotalBeds = 3
                        },
                        new
                        {
                            Id = 17,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "mix",
                            RoomNumber = "101",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        },
                        new
                        {
                            Id = 18,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2800m,
                            Residence = "mix",
                            RoomNumber = "102",
                            RoomType = "Double",
                            Size = "28m²",
                            TotalBeds = 2
                        },
                        new
                        {
                            Id = 19,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 2200m,
                            Residence = "mix",
                            RoomNumber = "103",
                            RoomType = "Triple",
                            Size = "35m²",
                            TotalBeds = 3
                        },
                        new
                        {
                            Id = 20,
                            Floor = 1,
                            OccupiedBeds = 0,
                            Price = 3500m,
                            Residence = "mix",
                            RoomNumber = "104",
                            RoomType = "Single",
                            Size = "20m²",
                            TotalBeds = 1
                        });
                });

            modelBuilder.Entity("ThePleasantOcc.Models.Booking", b =>
                {
                    b.HasOne("ThePleasantOcc.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ThePleasantOcc.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
